on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  post-summaries:
    runs-on: ubuntu-latest
    env:
      DEEPL_AUTHKEY: ${{ secrets.DEEPL_AUTHKEY }}
      GH_APPID: ${{ secrets.GH_APPID }}
      GH_APPKEY: ${{ secrets.GH_APPKEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run the Bot
        run: python arxiv_bot.py
